---
__postgresql_version: "{{ hostvars['database'].postgresql_version }}"
__postgresql_data_dir: "{{ hostvars['database'].postgresql_data_dir }}"
__postgresql_bin_path: "/usr/lib/postgresql/{{ __postgresql_version }}/bin"
__postgresql_config_path: "/etc/postgresql/{{ __postgresql_version }}/main"
__postgresql_daemon: postgresql
__postgresql_packages:
  - postgresql
  - postgresql-contrib
  - libpq-dev
postgresql_python_library: python3-psycopg2
