---
- name: Install Docker on ubuntu
  when: inventory_hostname == "ec2-34-205-129-46.compute-1.amazonaws.com"
  include_tasks:
    file: docker_ubuntu.yml

- name: Install Docker on centos
  when: inventory_hostname == "ec2-52-91-80-170.compute-1.amazonaws.com"
  include_tasks:
    file: docker_centos.yml
